version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-docker:1.0.0
    container_name: demo
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - PORT:${PORT}
